#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint
if [ $? -ne 0 ]; then
  echo "Lint failed. Commit aborted."
  exit 1
fi

tsccmd="tsc --noEmit"
if npm run | grep -q "type-check"; then
  tsccmd="npm run type-check"
fi

$tsccmd
if [ $? -ne 0 ]; then
  echo "Type check failed. Commit aborted."
  exit 1
fi
